service: push-code
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: prod
  region: us-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:*
      Resource:
        - !GetAtt WorkQueue.Arn
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - !Ref GitCredential

  environment:
    PUSHCODE_WORK_QUEUE: !Ref WorkQueue
    CJ_PUSHCODE_GIT_CREDENTIALS_ID: !Join
        - "/"
        - - !Ref AWS::StackName
          - GitCredential


package:
  individually: true

plugins:
  - serverless-rust

functions:
  accept:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: aws-push-code.accept
    events:
      - http:
          path: '/push-code'
          method: POST
  work:
    handler: aws-push-code.work
    memorySize: 2048
    events:
      - sqs:
          arn: !GetAtt WorkQueue.Arn
    vpc:
          securityGroupIds:
            - !ImportValue network-AttachedNetworkDefaultSecurityGroup
          subnetIds:
            - !ImportValue network-AttachedNetworkLeftSubnet
            - !ImportValue network-AttachedNetworkRightSubnet

resources:
  Resources:
    WorkQueue:
      Type: AWS::SQS::Queue
    SourceStore:
      Type: AWS::S3::Bucket
      Properties:
          VersioningConfiguration:
              Status: Enabled
    GitCredential:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: !Join
          - "/"
          - - !Ref AWS::StackName
            - GitCredential
        SecretString: "REPLACEME"

